modLoader="javafml"
loaderVersion="${forge_range}"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="template"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits="${mod_credits}"
description='''${mod_description}'''
logoFile="assets/logo.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION" # MATCH_VERSION/IGNORE_SERVER_VERSION/IGNORE_ALL_VERSION/NONE

[[dependencies.template]]
modId="minecraft"
mandatory=true
versionRange="${mc_range}"
ordering="NONE" # BEFORE/AFTER/NONE
side="BOTH" # CLIENT/SERVER/BOTH

[[dependencies.template]]
modId="forge"
mandatory=true
versionRange="${forge_range}"
ordering="NONE"
side="BOTH"