org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

curseforge_id=
modrinth_id=
release_type=release

mod_id=template
mod_group=net.invictusslayer.template
mod_version=0.0.0
mod_name=Template
mod_authors=InvictusSlayer
mod_credits=
mod_license=MIT
mod_description=Template description.
homepage_url=https://github.com/InvictusSlayer/Multiloader-Project-Template/wiki
source_url=https://github.com/InvictusSlayer/Multiloader-Project-Template
issue_url=https://github.com/InvictusSlayer/Multiloader-Project-Template/issues

mc_version=1.20.1
mc_range=[1.20.1]
java_version=17

fabric_version=0.92.7+1.20.1
fabric_loader=0.18.4

forge_version=47.4.0
forge_range=[47,)

parch_mc_version=1.20.1
parch_version=2023.09.03